from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class Capability(str, Enum):
    SALES = "SALES"
    BUSINESS_SHIFTS = "BUSINESS_SHIFTS"
    ORDERS = "ORDERS"
    ORDER_ITEMS = "ORDER_ITEMS"
    ORDER_EVENTS = "ORDER_EVENTS"
    PAYMENTS = "PAYMENTS"
    RETURNS = "RETURNS"
    DISCOUNTS = "DISCOUNTS"
    GUEST_COUNT = "GUEST_COUNT"
    CURRENT_BUSINESS_SHIFT = "CURRENT_BUSINESS_SHIFT"
    OPEN_ORDERS = "OPEN_ORDERS"
    CURRENT_ORDER_TOTAL = "CURRENT_ORDER_TOTAL"
    TABLES = "TABLES"
    RESTAURANT_SECTIONS = "RESTAURANT_SECTIONS"
    ORDER_HISTORY = "ORDER_HISTORY"
    REALTIME_ORDER_UPDATES = "REALTIME_ORDER_UPDATES"

    EMPLOYEES = "EMPLOYEES"
    EMPLOYEE_ATTENDANCE = "EMPLOYEE_ATTENDANCE"
    EMPLOYEE_ROLES = "EMPLOYEE_ROLES"

    PRODUCTS = "PRODUCTS"
    PRODUCT_GROUPS = "PRODUCT_GROUPS"
    PRODUCT_PRICES = "PRODUCT_PRICES"
    MODIFIERS = "MODIFIERS"
    PRODUCT_VARIANTS = "PRODUCT_VARIANTS"
    EXTERNAL_MENUS = "EXTERNAL_MENUS"
    STOP_LISTS = "STOP_LISTS"
    COMBOS = "COMBOS"
    RECIPES = "RECIPES"

    WAREHOUSES = "WAREHOUSES"
    STOCK_BALANCES = "STOCK_BALANCES"
    STOCK_MOVEMENTS = "STOCK_MOVEMENTS"
    SUPPLIERS = "SUPPLIERS"
    PURCHASES = "PURCHASES"
    WRITEOFFS = "WRITEOFFS"
    INVENTORY = "INVENTORY"

    EXTERNAL_VENUES = "EXTERNAL_VENUES"
    SALE_PLACES = "SALE_PLACES"
    TERMINALS = "TERMINALS"
    STORES = "STORES"

    ORDER_CREATE = "ORDER_CREATE"
    ORDER_UPDATE = "ORDER_UPDATE"
    ORDER_CLOSE = "ORDER_CLOSE"
    ORDER_CANCEL = "ORDER_CANCEL"

    DELIVERY_ORDERS = "DELIVERY_ORDERS"
    DELIVERY_DRAFTS = "DELIVERY_DRAFTS"
    DELIVERY_RESTRICTIONS = "DELIVERY_RESTRICTIONS"
    DELIVERY_COURIERS = "DELIVERY_COURIERS"
    COURIER_LOCATIONS = "COURIER_LOCATIONS"

    WEBHOOKS = "WEBHOOKS"
    COMMANDS = "COMMANDS"
    COMMAND_STATUS = "COMMAND_STATUS"
    REVISION_SYNC = "REVISION_SYNC"

    PAGINATION = "PAGINATION"
    SERVER_TIME_FILTER = "SERVER_TIME_FILTER"
    SORTING = "SORTING"
    SOURCE_VERSION = "SOURCE_VERSION"
    UPDATED_SINCE = "UPDATED_SINCE"


class CapabilityState(str, Enum):
    SUPPORTED = "SUPPORTED"
    DERIVED = "DERIVED"
    UNAVAILABLE = "UNAVAILABLE"
    DEGRADED = "DEGRADED"
    UNKNOWN = "UNKNOWN"


@dataclass(frozen=True, slots=True)
class CapabilityProbe:
    capability: Capability
    state: CapabilityState
    checked_at: datetime
    last_success_at: datetime | None = None
    last_error_code: str | None = None
    evidence_summary: str | None = None

    def __post_init__(self) -> None:
        if self.state is CapabilityState.SUPPORTED and not self.evidence_summary:
            raise ValueError("SUPPORTED capability requires probe evidence")
