"""init schema

Revision ID: f844727060f4
Revises: 
Create Date: 2026-02-10 00:30:49.973420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f844727060f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('group', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('system_role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permission_code', sa.String(length=80), nullable=False),
    sa.Column('is_granted_by_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission_code', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_defaults_permission_code'), 'role_permission_defaults', ['permission_code'], unique=False)
    op.create_table('venue_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('venue_role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'user_id', name='uq_venue_member')
    )
    op.create_index(op.f('ix_venue_members_user_id'), 'venue_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_venue_members_venue_id'), 'venue_members', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_members_venue_id'), table_name='venue_members')
    op.drop_index(op.f('ix_venue_members_user_id'), table_name='venue_members')
    op.drop_table('venue_members')
    op.drop_index(op.f('ix_role_permission_defaults_permission_code'), table_name='role_permission_defaults')
    op.drop_table('role_permission_defaults')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('permissions')
    # ### end Alembic commands ###
